# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "kennasecurity/27-cloud-base"

  config.vm.network "private_network", type: "dhcp"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 8180, host: 8180
  #config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8090, host: 8090
  config.vm.network "forwarded_port", guest: 5050, host: 5050
  config.vm.network "forwarded_port", guest: 5075, host: 5075
  config.vm.network "forwarded_port", guest: 7878, host: 7878
  config.vm.network "forwarded_port", guest: 8280, host: 8280

  config.vm.synced_folder ".", "/vagrant", id: "vagrant"
  config.vm.synced_folder "../../", "/freckles", id: "freckles"
  config.vm.synced_folder "../../../frkl", "/frkl", id: "frkl"
  config.vm.synced_folder "../../../luci", "/luci", id: "luci"
  config.vm.synced_folder "../../../nsbl", "/nsbl", id: "nsbl"
  config.vm.synced_folder "../../../repos", "/repos", id: "repos"
  config.vm.synced_folder "../../../roles", "/roles", id: "roles"
  config.vm.synced_folder "../../../examples", "/examples", id: "examples"
  config.vm.synced_folder "../../../sites", "/sites", id: "sites"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

end
