# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

#  if Vagrant.has_plugin?("vagrant-proxyconf")
#    config.proxy.http     = "http://10.0.0.14:3128/"
#    config.proxy.https    = "http://10.0.0.14:3128/"
#    config.apt_proxy.http = "http://10.0.0.11:3142"
#    config.apt_proxy.https = "http://10.0.0.11:3142"
#    config.proxy.no_proxy = "localhost,127.0.0.1,.lan"
#  end

  # Vagrant.configure('2') do |config|
  #   config.cache.scope = :box
  #   config.proxy.enabled = true
  #   config.ca_certificates.enabled = true
  #   # config.ca_certificates.certs = Dir.glob('/etc/pki/ca-trust/source/anchors/*.crt')
  #   config.ca_certificates.certs = Dir.glob('/etc/ssl/certs/*.pem')
  # end

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "fujimakishouten/debian-stretch64"
  #config.vm.box = "freckles-dev"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
#  config.vm.network "forwarded_port", guest: 80, host: 8090
#  config.vm.network "forwarded_port", guest: 81, host: 8091
#  config.vm.network "forwarded_port", guest: 9191, host: 9191
#  config.vm.network "forwarded_port", guest: 8888, host: 8888
#  config.vm.network "forwarded_port", guest: 9090, host: 9090

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"


  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  #config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", id: "vagrant"
  config.vm.synced_folder "../../", "/freckles", id: "freckles"
  config.vm.synced_folder "../../../frkl", "/frkl", id: "frkl"
  config.vm.synced_folder "../../../nsbl", "/nsbl", id: "nsbl"
  config.vm.synced_folder "../../../inaugurate", "/inaugurate", id: "inaugurate"
  #config.vm.synced_folder "../../../frecklets", "/frecklets", id: "frecklets"


  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # config.proxy.enabled = false
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
  sudo rm -f /etc/apt/sources.list.d/unstable.list

  wget -O- https://freckles.io | sudo bash -s -- freckelize --help
  #wget -O- https://freckles.io | sudo bash -s -- freckelize dotfiles -i terminal/minimal -f gh:makkus/dotfiles
  SHELL
  #config.vm.provision :shell, path: "vagrant_bootstrap.sh", privileged: false
end
